# Analysing results of training

After running each of the notebooks that implement a ship finding pipeline we can import all the results from them and analyse them here.

In [1]:
import papermill as pm

In [2]:
nbs = pm.read_notebooks('.')

In [4]:
nbs.dataframe

,name,value,type,filename,key
0,epochs,10,record,20-ml-baseline.ipynb,20-ml-baseline.ipynb
1,name,conv-net,record,20-ml-baseline.ipynb,20-ml-baseline.ipynb
2,test_accuracy,0.941429,record,20-ml-baseline.ipynb,20-ml-baseline.ipynb
3,train_accuracy,0.938571,record,20-ml-baseline.ipynb,20-ml-baseline.ipynb
4,n_estimators,10,record,21-random-forest.ipynb,21-random-forest.ipynb
5,name,random forest,record,21-random-forest.ipynb,21-random-forest.ipynb
6,test_accuracy,0.945714,record,21-random-forest.ipynb,21-random-forest.ipynb
7,train_accuracy,0.99873,record,21-random-forest.ipynb,21-random-forest.ipynb
8,alpha,0.0001,record,23-logistic-regression.ipynb,23-logistic-regression.ipynb
9,loss,hinge,record,23-logistic-regression.ipynb,23-logistic-regression.ipynb
10,max_iter,50,record,23-logistic-regression.ipynb,23-logistic-regression.ipynb
11,penalty,l2,record,23-logistic-regression.ipynb,23-logistic-regression.ipynb
12,test_accuracy,0.917143,record,23-logistic-regression.ipynb,23-logistic-regression.ipynb
13,train_accuracy,0.968571,record,23-logistic-regression.ipynb,23-logistic-regression.ipynb
14,n_estimators,50,record,24-extra-trees.ipynb,24-extra-trees.ipynb
15,name,random forest,record,24-extra-trees.ipynb,24-extra-trees.ipynb
16,test_accuracy,0.968571,record,24-extra-trees.ipynb,24-extra-trees.ipynb
17,train_accuracy,1,record,24-extra-trees.ipynb,24-extra-trees.ipynb

In [6]:
nbs.dataframe[nbs.dataframe.name == 'test_accuracy']

,name,value,type,filename,key
2,test_accuracy,0.941429,record,20-ml-baseline.ipynb,20-ml-baseline.ipynb
6,test_accuracy,0.945714,record,21-random-forest.ipynb,21-random-forest.ipynb
12,test_accuracy,0.917143,record,23-logistic-regression.ipynb,23-logistic-regression.ipynb
16,test_accuracy,0.968571,record,24-extra-trees.ipynb,24-extra-trees.ipynb